cc_binary(
    name = "base64",
    srcs = ["base64.cc"],
    deps = [
        "@abseil-cpp//absl/strings",
        "@trunk//base:flags",
        "@trunk//io:file-utils",
        "@trunk//io:native-file",
    ],
)
